import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins, Cormorant } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-poppins",
});

const cormorant = Cormorant({
  subsets: ["latin"],
  weight: ["300", "400"],
  variable: "--font-cormorant",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${cormorant.variable}`}>
        {children}
      </body>
    </html>
  );
}

